# render.yaml

services:
  - type: web
    name: my-python-service
    env: production
    plan: starter
    runtime: python  # Specify the correct runtime for Python
    buildCommand: pip install -r requirements.txt  # Command to install dependencies
    startCommand: python app.py  # Command to start your application
    envVars:
      - key: FLASK_ENV
        value: production  # Example for Flask applications
      - key: DATABASE_URL
        value: ${DATABASE_URL}  # Ensure this variable is set
    autoDeploy: true
<<<<<<< HEAD
    regions:
      - us-west-2
=======
    
>>>>>>> origin/main
