# render.yaml

services:
  - type: web
    name: my-web-service
    env: production
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      NODE_ENV: production
    autoDeploy: true
    regions:
      - us-west-2

